import * as THREE from 'https://cdn.jsdelivr.net/npm/three@0.170.0/build/three.module.js';
const $=s=>document.querySelector(s),scene=new THREE.Scene(),camera=new THREE.PerspectiveCamera(62,innerWidth/innerHeight,.1,700),renderer=new THREE.WebGLRenderer({antialias:true});
renderer.setPixelRatio(Math.min(devicePixelRatio,2));renderer.setSize(innerWidth,innerHeight);renderer.shadowMap.enabled=true;document.body.prepend(renderer.domElement);
scene.background=new THREE.Color(0x789b84);scene.fog=new THREE.FogExp2(0x789b84,.012);
scene.add(new THREE.HemisphereLight(0xbde8ff,0x152719,1.5));const sun=new THREE.DirectionalLight(0xfff0cc,2.2);sun.position.set(-50,80,30);sun.castShadow=true;scene.add(sun);
const ground=new THREE.Mesh(new THREE.PlaneGeometry(220,220),new THREE.MeshStandardMaterial({color:0x203d27,roughness:1}));ground.rotation.x=-Math.PI/2;ground.receiveShadow=true;scene.add(ground);
let seed=Date.now()&0xfffffff;const rnd=()=>{seed|=0;seed=(seed+0x6D2B79F5)|0;let z=seed;z=Math.imul(z^(z>>>15),z|1);z^=z+Math.imul(z^(z>>>7),z|61);return((z^(z>>>14))>>>0)/4294967296};
const M=c=>new THREE.MeshStandardMaterial({color:c,roughness:.9}),resources=[],enemies=[],particles=[];
function tree(x,z,s){let g=new THREE.Group(),tr=new THREE.Mesh(new THREE.CylinderGeometry(.22,.32,2.2,7),M(0x5b3c25));tr.position.y=1.1;tr.castShadow=true;g.add(tr);for(let i=0;i<3;i++){let c=new THREE.Mesh(new THREE.ConeGeometry(1.25-i*.2,2.2,7),M(i===2?0x244f2e:0x1d672f));c.position.y=2.2+i*.75;c.castShadow=true;g.add(c)}g.position.set(x,0,z);g.scale.setScalar(s);scene.add(g)}
for(let i=0;i<220;i++){let x=(rnd()-.5)*190,z=(rnd()-.5)*190;if(Math.hypot(x,z)>11)tree(x,z,.65+rnd()*1.15)}
function resource(type,x,z){let c={wood:0x9b663b,stone:0x89939a,berries:0xe84767,water:0x36b9e8}[type],geo=type==='wood'?new THREE.CylinderGeometry(.18,.28,1.2,7):new THREE.IcosahedronGeometry(type==='stone'?.42:.34,1),m=new THREE.Mesh(geo,M(c));m.position.set(x,.4,z);m.castShadow=true;m.userData={type,phase:rnd()*6};scene.add(m);resources.push(m)}
for(let i=0;i<100;i++)resource(['wood','wood','stone','berries','water'][Math.floor(rnd()*5)],(rnd()-.5)*175,(rnd()-.5)*175);
const player=new THREE.Group(),body=new THREE.Mesh(new THREE.CapsuleGeometry(.42,1,5,10),M(0xdce9e3)),head=new THREE.Mesh(new THREE.SphereGeometry(.35,12,8),M(0xffc79c));
body.position.y=1;head.position.y=1.8;body.castShadow=head.castShadow=true;player.add(body,head);player.position.set(0,0,8);scene.add(player);
function enemy(x,z){let g=new THREE.Group(),b=new THREE.Mesh(new THREE.SphereGeometry(.55,12,8),M(0x3d1e22)),e=new THREE.Mesh(new THREE.SphereGeometry(.13,8,6),M(0xff4c4c));b.position.y=.6;e.position.set(0,.75,.48);b.castShadow=true;g.add(b,e);g.position.set(x,0,z);g.userData={hp:3,spd:1.4+rnd()*1.2};scene.add(g);enemies.push(g)}
for(let i=0;i<12;i++)enemy((rnd()-.5)*130,(rnd()-.5)*130);
const fire=new THREE.PointLight(0xff8b32,3,10);fire.position.set(6,2,3);scene.add(fire);let f=new THREE.Mesh(new THREE.CylinderGeometry(.7,.35,.2,8),M(0x653c22));f.position.set(6,.1,3);scene.add(f);
const stats=Object.assign({hp:100,hunger:100,thirst:100,stamina:100,wood:0,stone:0,berries:0,water:0,day:1,objective:0},JSON.parse(localStorage.getItem('forgottenForestSave')||'{}'));
const keys={};let yaw=0,gameTime=0,last=performance.now(),cool=0,drag=false,lx=0;
addEventListener('keydown',e=>{keys[e.key.toLowerCase()]=true;if(e.key.toLowerCase()==='e')interact()});addEventListener('keyup',e=>keys[e.key.toLowerCase()]=false);
renderer.domElement.onpointerdown=e=>{drag=true;lx=e.clientX};addEventListener('pointerup',()=>drag=false);addEventListener('pointermove',e=>{if(drag){yaw-=(e.clientX-lx)*.006;lx=e.clientX}});
document.querySelectorAll('[data-key]').forEach(b=>{let k=b.dataset.key;b.onpointerdown=()=>keys[k]=true;b.onpointerup=b.onpointerleave=()=>keys[k]=false});
document.querySelector('#lookL').onpointerdown=()=>yaw+=.2;document.querySelector('#lookR').onpointerdown=()=>yaw-=.2;document.querySelector('#action').onclick=interact;
document.querySelector('#share').onclick=async()=>{let text=`I am surviving The Forgotten Forest — Day ${stats.day}.`;if(navigator.share){try{await navigator.share({title:'The Forgotten Forest',text,url:location.href})}catch{}}else{await navigator.clipboard?.writeText(text+' '+location.href);say('Share text copied')}};
function say(s){let e=$('#message');e.textContent=s;e.classList.remove('show');void e.offsetWidth;e.classList.add('show')}
function save(){localStorage.setItem('forgottenForestSave',JSON.stringify(stats))}
function interact(){if(cool>0)return;cool=.3;let n=null,d=3;for(let r of resources){if(r.parent){let q=r.position.distanceTo(player.position);if(q<d){n=r;d=q}}}if(n){let type=n.userData.type;stats[type]++;scene.remove(n);say('+1 '+type.toUpperCase());save();return}for(let e of enemies){if(e.position.distanceTo(player.position)<2.5){e.userData.hp--;if(e.userData.hp<=0){scene.remove(e);enemies.splice(enemies.indexOf(e),1);say('CREATURE DEFEATED')}else say('HIT!');return}}if(player.position.distanceTo(new THREE.Vector3(6,0,3))<4){stats.hunger=Math.min(100,stats.hunger+18);stats.thirst=Math.min(100,stats.thirst+25);stats.hp=Math.min(100,stats.hp+8);say('CAMPFIRE RESTORED YOU')}}
function ui(){$('#hp').textContent=Math.round(stats.hp);$('#hunger').textContent=Math.round(stats.hunger);$('#thirst').textContent=Math.round(stats.thirst);$('#stamina').textContent=Math.round(stats.stamina);$('#wood').textContent=stats.wood;$('#stone').textContent=stats.stone;$('#berries').textContent=stats.berries;$('#water').textContent=stats.water;$('#day').textContent=stats.day;$('#objective').textContent=stats.objective<8?'Explore, gather resources and stay alive.':'The forest is deeper now. Find the hidden ruins.'}
function update(dt){gameTime+=dt;cool=Math.max(0,cool-dt);let f=(keys.w||keys.arrowup?1:0)-(keys.s||keys.arrowdown?1:0),r=(keys.d||keys.arrowright?1:0)-(keys.a||keys.arrowleft?1:0),l=Math.hypot(f,r)||1;f/=l;r/=l;let sprint=keys.shift&&stats.stamina>1,spd=sprint?7:4;stats.stamina=THREE.MathUtils.clamp(stats.stamina+(sprint?-13:9)*dt,0,100);let dir=new THREE.Vector3(r,0,f).applyAxisAngle(new THREE.Vector3(0,1,0),yaw);player.position.addScaledVector(dir,spd*dt);player.position.x=THREE.MathUtils.clamp(player.position.x,-104,104);player.position.z=THREE.MathUtils.clamp(player.position.z,-104,104);if(f||r)player.rotation.y=Math.atan2(dir.x,dir.z);
stats.hunger=Math.max(0,stats.hunger-.55*dt);stats.thirst=Math.max(0,stats.thirst-.75*dt);if(stats.hunger<15||stats.thirst<15)stats.hp=Math.max(0,stats.hp-1.5*dt);if(stats.hp<=0){stats.hp=70;stats.hunger=60;stats.thirst=60;player.position.set(0,0,8);say('YOU COLLAPSED — BACK AT CAMP')};
let cycle=(gameTime%90)/90,ang=cycle*Math.PI*2;sun.position.set(Math.cos(ang)*70,Math.sin(ang)*80+10,30);sun.intensity=Math.max(.15,Math.sin(ang)*1.8+.3);let night=1-Math.max(0,Math.sin(ang));scene.background.lerp(new THREE.Color(0x050b12),night*.8);scene.fog.color.copy(scene.background);
let nd=1+Math.floor(gameTime/90);if(nd>stats.day){stats.day=nd;stats.objective++;say('DAY '+stats.day);save()}
for(let r of resources)if(r.parent)r.position.y=.4+Math.sin(gameTime*2+r.userData.phase)*.08;
for(let e of enemies){let d=e.position.distanceTo(player.position);if(d<18){let v=player.position.clone().sub(e.position).setY(0).normalize();e.position.addScaledVector(v,e.userData.spd*dt);if(d<1.2)stats.hp=Math.max(0,stats.hp-8*dt)}}
let target=player.position.clone().add(new THREE.Vector3(0,4.2,8.5).applyAxisAngle(new THREE.Vector3(0,1,0),yaw));camera.position.lerp(target,1-Math.pow(.001,dt));camera.lookAt(player.position.x,player.position.y+1.1,player.position.z);ui();save()}
function loop(now){let dt=Math.min(.05,(now-last)/1000);last=now;update(dt);renderer.render(scene,camera);requestAnimationFrame(loop)}
addEventListener('resize',()=>{camera.aspect=innerWidth/innerHeight;camera.updateProjectionMatrix();renderer.setSize(innerWidth,innerHeight)});setTimeout(()=>$('#loading').classList.add('hidden'),700);ui();requestAnimationFrame(loop);
